// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"go-micro-sample/bff/client"
	"go-micro-sample/bff/lib/config"
)

// Injectors from wire.go:

func InitializeTodoService() client.ITodoService {
	todoConfig := config.NewTodoConfig()
	iTodoService := client.NewTodoService(todoConfig)
	return iTodoService
}

func InitializeUserService() client.IUserService {
	userConfig := config.NewUserConfig()
	iUserService := client.NewUserService(userConfig)
	return iUserService
}
